[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ativa depuração para encontrar problemas
[build.environment]
  NETLIFY_NEXT_PLUGIN_DEBUG = "true"
  NODE_VERSION = "20"

# Regras específicas para assets estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# IMPORTANTE: Não redirecionamos /_next/* para index.html
# Esta é a principal correção para os erros de carregamento JS
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

# Redirecionamento SPA apenas para rotas da aplicação, não para arquivos estáticos
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 