# Configurações do Netlify para Next.js com Supabase Auth
[build]
  command = "npm run build"
  publish = ".next"

# Configuração de ambiente de Node
[build.environment]
  NODE_VERSION = "18.18.0"  # Versão compatível com o Next.js mais recente

# Plugin do Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Definições de cache para conteúdo estático do Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirecionamentos para SPA e lidar com rotas do Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Permitir acesso a arquivos estáticos
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Redirecionar para a página de dashboard após login bem-sucedido
[[redirects]]
  from = "/_supabase/auth/v1/callback"
  to = "/dashboard"
  status = 302
  force = true

# Fallback para permitir que o Next.js lide com rotas internas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 