[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ativa depuração para encontrar problemas
[build.environment]
  NETLIFY_NEXT_PLUGIN_DEBUG = "true"
  NODE_VERSION = "16"

# Regras específicas para assets estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
  
# Garantir que rotas SPA sejam tratadas adequadamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 