[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configura regras específicas para os arquivos estáticos do Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configura regras de fallback para rotas dinâmicas
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Adiciona regra para páginas que não existem
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404 